import Head from 'next/head';
import Image from 'next/image';
import { Inter } from 'next/font/google';
import styles from '@/styles/Home.module.scss';

import Button from '@mui/material/Button';
import AddIcon from '@mui/icons-material/Add';
import { ChangeEvent, FormEvent, useState } from 'react';
import { Box, Container, Grid, Paper, TextField, styled } from '@mui/material';
import SendIcon from '@mui/icons-material/Send';

const inter = Inter({ subsets: ['latin'] });

// https://www.youtube.com/watch?v=uRQH2CFvedY

type Message = {
  role: 'user' | 'assistant' | null;
  content: string | null;
};

// PRAGMA foreign_keys = ON;

// TODO:
//  * sqlite3 // npm
//  * mysql: insert, select (where from), delete
//  * front <---> backend <---> baza
//  * https://sqlitebrowser.org/
//  * sqlite3 orm node

export default function Home() {
  const [value, setValue] = useState<string>('');

  const [messages, setMessages] = useState<Message[] | []>([
    {
      role: 'user',
      content:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt perferendis veritatis, asperiores molestias aut vel accusantium quae unde eveniet quo, a eum? Consequatur veniam aut quasi amet quia dicta. Velit.',
    },
    {
      role: 'assistant',
      content:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt perferendis veritatis, asperiores molestias aut vel accusantium quae unde eveniet quo, a eum? Consequatur veniam aut quasi amet quia dicta. Velit.',
    },
    {
      role: 'user',
      content:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt perferendis veritatis, asperiores molestias aut vel accusantium quae unde eveniet quo, a eum? Consequatur veniam aut quasi amet quia dicta. Velit.',
    },
    {
      role: 'assistant',
      content:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt perferendis veritatis, asperiores molestias aut vel accusantium quae unde eveniet quo, a eum? Consequatur veniam aut quasi amet quia dicta. Velit.',
    },
    {
      role: 'user',
      content:
        'Lorem ipsum dolor sit amet consectetur adipisicing elit. Sunt perferendis veritatis, asperiores molestias aut vel accusantium quae unde eveniet quo, a eum? Consequatur veniam aut quasi amet quia dicta. Velit.',
    },
  ]);

  const handleValueChange = (e: ChangeEvent<HTMLInputElement>) => {
    setValue(e.target.value);
  };

  const handleMessagesSend = (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    setMessages([...messages, { role: 'user', content: value }]);
    fetchData();
  };

  const fetchData = async () => {
    const requestOptions = {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        messages: [...messages, { role: 'user', content: value }],
      }),
    };

    try {
      const resposne = await fetch(`http://localhost:3000/api/generate`, requestOptions);
      const data = await resposne.json();
      setMessages((currentMessages) => [...currentMessages, data.choices[0].message]);
      setValue('');
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main>
        <Box sx={{ flexGrow: 1, height: '100vh' }}>
          <Grid container sx={{ height: '100%' }} spacing={2}>
            <Grid item xs={4}>
              <Button className={styles.button} color='info' fullWidth variant='outlined' startIcon={<AddIcon />}>
                new chat
              </Button>

              <nav>chat history</nav>
            </Grid>
            <Grid item xs={8}>
              {messages.map((message, index) => {
                return (
                  <Box sx={{ bgcolor: '#cfe8fc', marginBottom: '1rem' }} key={index}>
                    {message.role === 'user' && (
                      <Paper key={index} elevation={4} sx={{ padding: '0.5rem', position: 'relative' }}>
                        <Image
                          src={'/user.webp'}
                          alt={''}
                          width={48}
                          height={48}
                          style={{
                            borderRadius: '50%',
                            position: 'absolute',
                            top: '0',
                            left: '-56px',
                          }}
                        />

                        {message.content}
                      </Paper>
                    )}
                    {message.role === 'assistant' && (
                      <Paper key={index} elevation={4} sx={{ padding: '0.5rem', position: 'relative' }}>
                        <Image
                          src={'/assistant.svg'}
                          alt={''}
                          width={48}
                          height={48}
                          style={{
                            borderRadius: '50%',
                            position: 'absolute',
                            top: '0',
                            left: '-56px',
                            backgroundColor: '#19c37d',
                            padding: '8px',
                          }}
                        />
                        {message.content}
                      </Paper>
                    )}
                  </Box>
                );
              })}
              <form onSubmit={handleMessagesSend}>
                <TextField value={value} placeholder='Send message' onChange={handleValueChange} multiline maxRows={4} />
                <Button size='large' type='submit'>
                  <SendIcon />
                </Button>
              </form>
            </Grid>
          </Grid>
        </Box>
      </main>
    </>
  );
}
